include:
  - apps/aiostreams/compose.yaml
  - apps/authelia/compose.yaml
  - apps/beszel/compose.yaml
  - apps/dozzle/compose.yaml
  - apps/mediaflow-proxy/compose.yaml
  - apps/traefik/compose.yaml
  - apps/uptime-kuma/compose.yaml
  - apps/warp/compose.yaml

networks:
  default:
    external: ${DOCKER_NETWORK_EXTERNAL:-false}
    name: ${DOCKER_NETWORK_NAME:-stremio-network}
