services:
  warp:
    image: caomingjun/warp:latest
    container_name: warp
    device_cgroup_rules:
      - "c 10:200 rwm"
    expose:
      - 1080
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${DOCKER_DATA_DIR}/warp:/var/lib/cloudflare-warp
    restart: unless-stopped
