services:
  beszel:
    image: henrygd/beszel:0.18
    container_name: beszel
    user: "$PUID:$PGID"
    ports:
      - "127.0.0.1:8090:8090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`${BESZEL_HOSTNAME?}`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.beszel.middlewares=authelia@docker"
    volumes:
      - ${DOCKER_DATA_DIR}/beszel/socket:/beszel_socket
      - ${DOCKER_DATA_DIR}/beszel/data:/beszel_data
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:0.18
    container_name: beszel-agent
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
    volumes:
      - ${DOCKER_DATA_DIR}/beszel/agent:/var/lib/beszel-agent
      - ${DOCKER_DATA_DIR}/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped
