services:
  beszel:
    image: henrygd/beszel:0.18
    container_name: beszel
    expose:
      - 8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`${BESZEL_HOSTNAME?}`)"
      - "traefik.http.routers.beszel.entrypoints=websecure"
      - "traefik.http.routers.beszel.tls.certresolver=letsencrypt"
    volumes:
      - ${DOCKER_DATA_DIR}/beszel/socket:/beszel_socket
      - ${DOCKER_DATA_DIR}/beszel/data:/beszel_data
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent:0.18
    container_name: beszel-agent
    network_mode: host
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - HUB_URL=http://beszel:8090
      - TOKEN="<TOKEN>"
      - KEY="<KEY>"
    volumes:
      - ${DOCKER_DATA_DIR}/beszel/agent:/var/lib/beszel-agent
      - ${DOCKER_DATA_DIR}/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
